### ISSUE TITLE
[BUG] App does not react to selecting adding book options

### ISSUE THREAD

**Issue by TechnoBloom** [mateusz-bak/openreads-android#251]
**Describe the bug**
Cannot add new books.

**To Reproduce**
Tap on the “+” button, then tap on any of the three options to add a book. After doing so, nothing happens.

**Expected behavior**
The screen to add a book manually, look for it in OpenLibrary or scan its barcode should appear.

**Additional info(please complete the following information):**
 - Manufacturer and model: Xiaomi Redmi 6A
 - Android version: 9 PPR1.180610.011
 - App version: 2.0.3
 - App source: F-Droid

**Additional context**
This only started happening after updating to version 2 of the app.

**Comment by TechnoBloom** [comment]
Hi, @mateusz-bak , all other functionalities work perfectly.

As you can see in the video, none of the three methods for adding a book work. Nonetheless, opening books, checking statistics, searching for books and opening the settings all work.

Thank you so much for your attention 🙏

https://user-images.githubusercontent.com/129879279/229854915-4df12f43-9cc5-4d81-b9c5-3b9a4761cda1.mp4

**Comment by mateusz-bak** [comment]
Just a guess but can you try uninstall and install again?

**Comment by TechnoBloom** [comment]
Hello,
I just tried doing that and still get the same error

**Comment by mateusz-bak** [comment]
Alright, I have two guesses why this could break. Unfortunately I cannot work on it now, I will create an .apk with possible fix and put it here next week.

**Comment by Sumitarp** [comment]
Thank you, if you put it an.apk

**Comment by mateusz-bak** [comment]
@Sumitarp can you provide me details of your phone and OS?

**Comment by Sumitarp** [comment]
> @Sumitarp can you provide me details of your phone and OS?
Redmi note 7s and android 10.

**Comment by mateusz-bak** [comment]
@Sumitarp  @TechnoBloom sorry for delay, please check if the issue occurs in this version:
[https://github.com/mateusz-bak/openreads-android/releases/download/251_1/app-release_251_1.apk](https://github.com/mateusz-bak/openreads-android/releases/download/251_1/app-release_251_1.apk)

**Comment by Sumitarp** [comment]
This version works fine, thank you very much for your help.

Sumit

**Comment by mateusz-bak** [comment]
@TechnoBloom yeah, you need to uninstall first. So the issue is fixed in the apk?

**Comment by TechnoBloom** [comment]
No, I still get the same error. For some reason, after installing the APK it says the version is 2.0.3 (if I'm not wrong it should be different) and the buttons still do not respond when I try to add new books.

**Comment by Sumitarp** [comment]
@TechnoBloom 

Hey, you can try updating your android version first or else you can provide me your device info.

**Comment by mateusz-bak** [comment]
@TechnoBloom it will show the same version I just changed code for this issue. If the issue still persists though I have no idea what causes it. I though the issue is the same for you both but at least @Sumitarp will have it working. I'll be releasing a new version in a couple of days.

**Comment by TechnoBloom** [comment]
> @TechnoBloom
> 
> Hey, you can try updating your android version first or else you can provide me your device info.

Hi, there seem to be no updates for my OS. This us the device info I have collected:

Device model: Redmi 6A

MIUI version: MIUI Global 11.0.8 | Stable 11.0.8.0(PCBMIXM)

Android version: 9 PPR1.180610.011

Android security patch level: 2020-05-01

**Comment by TechnoBloom** [comment]
> @TechnoBloom it will show the same version I just changed code for this issue. If the issue still persists though I have no idea what causes it. I though the issue is the same for you both but at least @Sumitarp will have it working. I'll be releasing a new version in a couple of days.

Thank you so much 🙏

**Comment by Sumitarp** [comment]
> > @TechnoBloom
> > 
> > Hey, you can try updating your android version first or else you can provide me your device info.
> 
> Hi, there seem to be no updates for my OS. This us the device info I have collected:
> 
> Device model: Redmi 6A
> 
> MIUI version: MIUI Global 11.0.8 | Stable 11.0.8.0(PCBMIXM)
> 
> Android version: 9 PPR1.180610.011
> 
> Android security patch level: 2020-05-01

I think it requires atleast android 10.
